### ISSUE TITLE
degnutil dependency missing and not installed in installation process

### ISSUE THREAD

**Issue by ianandersonlol** [degnbol/GASP#1]
Hi! Very interested in trying your GASP package, but I realized the installation process is missing your utility package. Would you happen to have it handy? Thanks!

**Comment by degnbol** [comment]
Hi Ian, it is a git submodule (located here: `https://bitbucket.org/Degnbol/degnlib/`).
If you have already cloned the repository you can run `git submodule update --init` to download, otherwise clone with the `--recurse-submodules` flag.
I will update the `install.sh` to run `git submodule update --init`.

**Comment by degnbol** [comment]
Fixed by commit f440eef

**Comment by ianandersonlol** [comment]
Thank you!!

**Comment by ianandersonlol** [comment]
Unfortunately that didn't seem to fix it. The missing util is degnutil not degnlib. I tried just renaming degnlib degnutil but it seems to have a completely empty __init__.py so it couldn't load the io module.

**Comment by degnbol** [comment]
degnutil is located at `degnlib/degnutil/`, although since only one function from there is used I simplified copied it over with commit b4001c2, let me know if this fixes things.
